_BASE_: "../Base-Distillation.yaml"
OUTPUT_DIR: output/ReviewGDKD-R50-R101

EXPERIMENT:
  TAG: ["ReviewGDKD", "R50", "R101"]

MODEL:
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  WEIGHTS: "pretrained/r50-r101.pth"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  ROI_HEADS:
    NAME: "StandardROIHeads"

TEACHER:
  MODEL:
    RESNETS:
      DEPTH: 101
KD:
  TYPE: "ReviewGDKD"
  REVIEWKD:
    KD_WEIGHT: 1.0

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  MAX_ITER: 180000
  STEPS:
    - 120000
    - 160000
